feature: voice channel support
BirbJS/Birb pull request #36
Opened 2021-12-22 17:08 UTC by knokbak

2021-12-22 18:25 UTC, axisiscool requested changes

2021-12-22 18:25 UTC, axisiscool commented on src/classes/VoiceChannel.ts
> +        }
```suggestion
        if ('user_limit' in data) this.userLimit = data.user_limit ?? null;
```

2021-12-22 18:25 UTC, axisiscool commented on src/classes/VoiceChannel.ts
> +        }
```suggestion
        if ('bitrate' in data) this.bitrate = data.bitrate;
```
The `{}` isn't needed and the logical or can be replaced with `??`.

2021-12-22 18:25 UTC, axisiscool commented on src/classes/VoiceState.ts
> +        }
```suggestion
        if ('session_id' in data) this.sessionId = data.session_id;
        if ('deaf' in data) this.deaf = data.deaf;
        if ('mute' in data) this.mute = data.mute;
        if ('self_deaf' in data) this.selfDeaf = data.self_deaf;
        if ('self_mute' in data) this.selfMute = data.self_mute;
        if ('self_stream' in data) this.streaming = data.self_stream;
        if ('self_video' in data) this.videoEnabled = data.self_video;
```

2021-12-22 18:25 UTC, axisiscool commented on src/classes/VoiceState.ts
> +        if (!this.member) this.member = await this.guild.members.fetch(this.memberId);
```suggestion
        this.member ??= await this.guild.members.fetch(this.memberId);
```

2021-12-22 18:31 UTC, axisiscool approved these changes

2021-12-22 18:40 UTC, knokbak commented
chore: add methods to voice channel support (e.g. disconnect, setMute, setDeaf, move) @BirbJS/team

2022-01-11 11:16 UTC, PalmDevs commented
anti stale!!!

2022-02-10 15:16 UTC, axisiscool commented
@knokbak Any chance you can work on this?

2022-02-23 02:16 UTC, closed without merging